services:
  migrations:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["poetry", "run", "alembic"]
    command: ["upgrade", "head"]
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/app/src
      - ./backend/migrations:/app/migrations
    networks:
      - backend-network

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  postgres-data:
