services:
  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"

  postgres:
    container_name: database
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: uptpgpw
      POSTGRES_USER: uptime
      POSTGRES_DB: uptime-db # Correct key is POSTGRES_DB, not POSTGRES_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  email-reader:
    container_name: email-api
    image: appsuptime:email-reader
    build:
      context: ./email_reader
      dockerfile: Dockerfile.dev
    env_file:
      - ./email_reader/.env
    volumes:
      - ./email_reader/src:/app/src
    ports:
      - "8001:80"
      - "5679:5679"
    environment:
      ENVIRONMENT: dev
      CACHE_CAPACITY_EMAIL_ID_LIST: 10
      CACHE_CAPACITY_EMAIL_MODEL_LIST: 3
      PAGE_SIZE: 20

  backend:
    container_name: uptime-api
    image: appsuptime:backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - "8000:80"
      - "5678:5678"
    depends_on:
      - postgres
      - email-reader
    environment:
      ENVIRONMENT: dev
      DATABASE_URL: "postgresql://uptime:uptpgpw@postgres:5432/uptime-db"
      EMAIL_PROCESSING_THREADS: 8

volumes:
  postgres-data:
