services:
  memcached:
    image: memcached:latest
    container_name: memcached

  postgres:
    container_name: database
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: uptpgpw
      POSTGRES_USER: uptime
      POSTGRES_DB: uptime-db # Correct key is POSTGRES_DB, not POSTGRES_DATABASE

  email-reader:
    container_name: email-api
    image: appsuptime:email-reader
    build:
      context: ./email_reader
      dockerfile: Dockerfile
    env_file:
      - ./email_reader/.env
    ports:
      - "8001:80"
    environment:
      ENVIRONMENT: prod
      CACHE_CAPACITY_EMAIL_ID_LIST: 10
      CACHE_CAPACITY_EMAIL_MODEL_LIST: 3
      PAGE_SIZE: 20

  backend:
    container_name: uptime-api
    image: appsuptime:backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - memcached
      - email-reader
    environment:
      ENVIRONMENT: prod
      DATABASE_URL: "postgresql://uptime:uptpgpw@postgres:5432/uptime-db"
      EMAIL_PROCESSING_THREADS: 8
